import type { Metadata, Viewport } from 'next';
import Script from 'next/script';
import { Fraunces, DM_Sans, JetBrains_Mono } from 'next/font/google';
import { business, serviceAreas, social } from '@/lib/site-data';
import Nav from '@/components/Nav';
import AnnouncementBar from '@/components/AnnouncementBar';
import './globals.css';

// Display — Fraunces (variable, opsz + SOFT for editorial feel)
const display = Fraunces({
  subsets: ['latin'],
  variable: '--font-display',
  weight: 'variable',
  axes: ['opsz', 'SOFT'],
  display: 'swap'
});
// Body — DM Sans (clean, modern, non-Inter)
const sans = DM_Sans({
  subsets: ['latin'],
  variable: '--font-sans',
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap'
});
// Mono — JetBrains Mono for prices, badges, eyebrows
const mono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
  weight: ['400', '500', '600', '700'],
  display: 'swap'
});

export const metadata: Metadata = {
  metadataBase: new URL(business.baseUrl),
  title: {
    default: 'Raindrops Greenery | New York Cannabis Delivery',
    template: '%s | Raindrops Greenery'
  },
  description:
    'Raindrops Greenery NY is a premium 21+ cannabis delivery experience for Manhattan plus Long Island City, Williamsburg, and Greenpoint with curated Flower, Pre-Rolls, and Edibles.',
  applicationName: 'Raindrops Greenery',
  authors: [{ name: business.tradeName }],
  creator: business.tradeName,
  publisher: business.legalName,
  keywords: [
    'Raindrops Greenery',
    'cannabis delivery New York',
    'NYC cannabis delivery',
    'Manhattan cannabis delivery',
    'Brooklyn cannabis delivery',
    'Queens cannabis delivery',
    'weed delivery NYC',
    'licensed NY dispensary',
    'flower NYC',
    'pre-rolls NYC',
    'edibles NYC'
  ],
  alternates: { canonical: '/' },
  manifest: '/manifest.json',
  icons: {
    icon: [{ url: '/assets/logo.jpg', type: 'image/jpeg' }],
    apple: [{ url: '/assets/logo.jpg' }],
    shortcut: ['/assets/logo.jpg']
  },
  openGraph: {
    // Image is auto-generated by app/opengraph-image.tsx (next/og edge render)
    title: 'Raindrops Greenery | New York Cannabis Delivery',
    description: 'Browse Raindrops NY Flower, Pre-Rolls, Edibles, delivery details, and customer guides.',
    url: business.baseUrl,
    siteName: 'Raindrops Greenery',
    locale: 'en_US',
    type: 'website'
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Raindrops Greenery | New York Cannabis Delivery',
    description: 'Premium 21+ delivery for Manhattan + East River neighborhoods.'
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, 'max-image-preview': 'large', 'max-snippet': -1 }
  },
  category: 'cannabis delivery'
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
  viewportFit: 'cover',
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#F5F1E8' },
    { media: '(prefers-color-scheme: dark)', color: '#0A1410' }
  ]
};

const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'LocalBusiness',
  '@id': `${business.baseUrl}#business`,
  name: business.tradeName,
  legalName: business.legalName,
  url: business.baseUrl,
  image: `${business.baseUrl}/assets/heroPhoto.jpg`,
  logo: `${business.baseUrl}/assets/logo.jpg`,
  telephone: business.phone,
  email: business.email,
  priceRange: '$$',
  address: {
    '@type': 'PostalAddress',
    addressRegion: 'NY',
    addressCountry: 'US'
  },
  areaServed: serviceAreas.map((area) => ({ '@type': 'City', name: area })),
  openingHoursSpecification: [
    {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
      opens: '10:00',
      closes: '22:00'
    }
  ],
  sameAs: social.map((item) => item.href)
};

const orgLd = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  '@id': `${business.baseUrl}#org`,
  name: business.legalName,
  url: business.baseUrl,
  logo: `${business.baseUrl}/assets/logo.jpg`,
  sameAs: social.map((item) => item.href)
};

const websiteLd = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  url: business.baseUrl,
  name: business.tradeName,
  potentialAction: {
    '@type': 'SearchAction',
    target: `${business.baseUrl}/menu?query={search_term_string}`,
    'query-input': 'required name=search_term_string'
  }
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${display.variable} ${sans.variable} ${mono.variable}`}>
      <head>
        {/* Preconnect to font CDN for snappier first paint (covered by next/font
            but the explicit hint helps in some browsers and crawlers). */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        {/* DNS-prefetch the Flowhub product image CDN so menu thumbs warm up. */}
        <link rel="dns-prefetch" href="https://storage.googleapis.com" />
      </head>
      <body className="font-[var(--font-sans)] antialiased">
        <noscript>
          <div style={{ background: '#0A1410', color: '#F5F1E8', padding: '16px 24px', textAlign: 'center', fontFamily: 'system-ui, -apple-system, sans-serif', fontSize: 14, lineHeight: 1.6 }}>
            This site uses JavaScript for the interactive menu, ZIP checker, and age verification. Please enable JavaScript, or call us at <strong style={{ color: '#C8E66E' }}>(888) 448-9717</strong> to order. 21+ only.
          </div>
        </noscript>
        <a href="#main" className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[120] focus:rounded-full focus:bg-[var(--rd-glow)] focus:px-4 focus:py-2 focus:text-xs focus:font-extrabold focus:uppercase focus:tracking-[0.16em] focus:text-[var(--rd-ink)]">
          Skip to content
        </a>
        <AnnouncementBar />
        <Nav />
        <Script id="ld-business" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
        <Script id="ld-org" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(orgLd) }} />
        <Script id="ld-website" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteLd) }} />
        {/*
          Analytics placeholders. Replace ga_id / pixel_id with real IDs before launch.
          GA4: https://support.google.com/analytics/answer/9304153
          Meta Pixel: https://www.facebook.com/business/help/952192354843755
        */}
        {process.env.NEXT_PUBLIC_GA_ID && (
          <>
            <Script src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_ID}`} strategy="afterInteractive" />
            <Script id="ga4" strategy="afterInteractive">
              {`window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}gtag('js', new Date());gtag('config', '${process.env.NEXT_PUBLIC_GA_ID}');`}
            </Script>
          </>
        )}
        {process.env.NEXT_PUBLIC_META_PIXEL_ID && (
          <Script id="meta-pixel" strategy="afterInteractive">
            {`!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,document,'script','https://connect.facebook.net/en_US/fbevents.js');fbq('init','${process.env.NEXT_PUBLIC_META_PIXEL_ID}');fbq('track','PageView');`}
          </Script>
        )}
        {children}
      </body>
    </html>
  );
}
